[package]
name = "tos"
version = "0.1.0"
authors = ["Tom Pinnock <tomj.pinnock@outlook.com>"]

[dependencies]
rlibc = "1.0"
volatile = "0.1.0"
spin = "0.4.5"
multiboot2 = "0.1.0"
bitflags = "0.7.0"
acpica-sys = "0.0.4"
x86_64 = "0.1.2"

[lib]
crate-type = ["staticlib"]